import { useState } from 'react';
import { SemesterCourse } from '../components/CourseSessionModal';
import { worksheetIdentityKey, normalizeCourse, dedupeCourses } from '../lib/sessionStore';
import { createWorkbook, worksheetFromCourse, writeLocalWorkbook, setActiveWorksheet, saveCloudWorkbook } from '../lib/workbookStore';
import { loadWorkbookFromExcelFile } from '../lib/exportUtils';

export function useWorkbookModals({ schemeRef, paperRef, authHeaders, clearYazaSessionHistory }: any) {
 const [modalType,setModalType]=useState<'new'|'continue'|null>(null),[pendingUpload,setPendingUpload]=useState<'scheme'|'paper'|null>(null),[showOldSessionModal,setShowOldSessionModal]=useState(false),[pendingGradeNavigation,setPendingGradeNavigation]=useState(false),[showNewCourseModal,setShowNewCourseModal]=useState(false),[showNewSessionModal,setShowNewSessionModal]=useState(false),[showCourseSelector,setShowCourseSelector]=useState(false);
 const openUploadModal=(type:'scheme'|'paper',course:SemesterCourse|null)=>{if(course){type==='scheme'?schemeRef.current?.triggerInput():paperRef.current?.triggerInput();return;}setPendingUpload(type);setModalType('new');};
 const triggerPendingUpload=()=>{if(pendingUpload==='scheme')schemeRef.current?.triggerInput();else if(pendingUpload==='paper')paperRef.current?.triggerInput();setPendingUpload(null);setModalType(null);};
 const closeModal=()=>{setPendingUpload(null);setModalType(null);};
 const handleSkipSemester=(reset:()=>void)=>{const upload=pendingUpload;setPendingUpload(null);setModalType(null);reset();if(upload==='scheme')schemeRef.current?.triggerInput();else if(upload==='paper')paperRef.current?.triggerInput();};
 const handleContinueSemester=()=>triggerPendingUpload(),handleStartNewFromContinue=()=>setModalType('new');
 const handleCreateNewWorksheet=(course:SemesterCourse,deps:any)=>{if(deps.confirmDiscardUnsavedWork&&!deps.confirmDiscardUnsavedWork('start a new course'))return;deps.setSemesterCourse(course);clearYazaSessionHistory(course.courseCode||'general');deps.setSessions((prev:SemesterCourse[])=>dedupeCourses([course,...prev.filter(s=>worksheetIdentityKey(s)!==worksheetIdentityKey(course))]));void deps.persistSession(course);deps.setStudentInfo((prev:any)=>({...prev,courseCode:course.courseCode||prev.courseCode,program:course.program||prev.program,year:course.year||prev.year,semester:course.semester||prev.semester}));deps.resetForNewSession();triggerPendingUpload();};
 const handleNewCourse=(updates:{courseCode:string;courseName:string},deps:any)=>{if(deps.confirmDiscardUnsavedWork&&!deps.confirmDiscardUnsavedWork('start a new course'))return;const courseCode=updates.courseCode.trim().toUpperCase(),courseName=updates.courseName.trim();if(!courseCode)return;if(!deps.workbook){alert('Please create or open a workbook before adding a course.');return;}const course:SemesterCourse={courseCode,courseName,program:'',year:'',semester:'',academicYear:'',sessionLabel:''};const sheet=worksheetFromCourse(course),saved=writeLocalWorkbook({...deps.workbook,sheets:[...deps.workbook.sheets,sheet],activeSheetId:sheet.id,updatedAt:new Date().toISOString()});deps.setWorkbook(saved);deps.setWorkbooks?.((prev:any[])=>[saved,...prev.filter(item=>item.id!==saved.id)]);deps.setActiveWorkbookId?.(saved.id);deps.setSemesterCourse(course);deps.setActiveSessionId(sheet.id);localStorage.setItem('redpen_active_workbook_id',saved.id);localStorage.setItem('redpen_active_worksheet_id',sheet.id);clearYazaSessionHistory(courseCode);deps.setStudentInfo((prev:any)=>({...prev,name:'',regNo:'',program:'',year:'',semester:'',courseCode,examDate:''}));deps.resetWorkspaceForNewCourse();setShowNewCourseModal(false);if(deps.token)void deps.persistWorkbook(saved);};
 const handleCreateNewWorkbook=(updates:any,deps:any)=>{if(deps.confirmDiscardUnsavedWork&&!deps.confirmDiscardUnsavedWork('start a new workbook'))return;const course:SemesterCourse={courseCode:updates.courseCode.trim().toUpperCase(),courseName:updates.courseName.trim(),program:'',year:updates.year,semester:updates.semester,academicYear:updates.academicYear,sessionLabel:updates.sessionLabel,customName:updates.customName.trim()||undefined};const sheet=worksheetFromCourse(course),wb=createWorkbook(course.customName||course.sessionLabel||course.courseCode||'RedPen Workbook',[sheet]),saved=writeLocalWorkbook(wb);deps.setWorkbook(saved);deps.setWorkbooks?.((prev:any[])=>[saved,...prev.filter(item=>item.id!==saved.id)]);deps.setActiveWorkbookId?.(saved.id);deps.setSemesterCourse(course);deps.setSessions(saved.sheets.map((s:any)=>normalizeCourse(s.course)));deps.setActiveSessionId(sheet.id);localStorage.setItem('redpen_active_workbook_id',saved.id);localStorage.setItem('redpen_active_worksheet_id',sheet.id);clearYazaSessionHistory(course.courseCode||'general');deps.setStudentInfo((prev:any)=>({...prev,name:'',regNo:'',program:'',year:course.year,semester:course.semester,courseCode:course.courseCode,examDate:''}));deps.resetWorkspaceForNewCourse();deps.setHasUnsavedResult(false);setShowNewSessionModal(false);if(deps.token)void saveCloudWorkbook(deps.token,saved).then(result=>{deps.setWorkbooks?.(result.workbooks?.map((item:any)=>writeLocalWorkbook(item)) || [saved]);}).catch(e=>console.error('Failed to save new workbook:',e));};
 const selectWorksheet=(course:SemesterCourse,deps:any)=>{if(deps.hasUnsavedResult&&!window.confirm('You have unsaved grading work.\n\nSwitching courses will clear it unless it has been saved.\n\nContinue switching courses?'))return;if(!deps.workbook)return;const sheet=deps.workbook.sheets.find((s:any)=>worksheetIdentityKey(s.course)===worksheetIdentityKey(course));if(!sheet)return;const saved=writeLocalWorkbook(setActiveWorksheet(deps.workbook,sheet.id));deps.setWorkbook(saved);deps.setSemesterCourse(normalizeCourse(sheet.course));deps.setActiveSessionId(sheet.id);localStorage.setItem('redpen_active_worksheet_id',sheet.id);deps.resetForCourseSwitch();setShowOldSessionModal(false);setPendingGradeNavigation(false);if(deps.token)void deps.persistWorkbook(saved);};
 const handleViewChange=(view:string,course:SemesterCourse|null,activeWorksheetId:string|null,setActiveView:(v:any)=>void)=>{if(view!=='grade'){setActiveView(view);return;}if(course&&activeWorksheetId){setActiveView('grade');return;}setPendingGradeNavigation(true);setShowOldSessionModal(true);};
 const handleLoadFromFile=(deps:any)=>{if(deps.confirmDiscardUnsavedWork&&!deps.confirmDiscardUnsavedWork('import another workbook'))return;const input=document.createElement('input');input.type='file';input.accept='.xlsx,.xls,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel';input.onchange=async(e)=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;try{if(!/\.(xlsx|xls)$/i.test(file.name)){alert('Please select a valid Excel (.xlsx or .xls) workbook.');return;}const imported=await loadWorkbookFromExcelFile(file);if(!imported?.sheets?.length){alert('No courses were found in this Excel workbook.');return;}const saved=writeLocalWorkbook({...imported,activeSheetId:null});deps.setWorkbook(saved);deps.setWorkbooks?.((prev:any[])=>[saved,...prev.filter(item=>item.id!==saved.id)]);deps.setActiveWorkbookId?.(saved.id);deps.setSessions(saved.sheets.map((s:any)=>normalizeCourse(s.course)));deps.setSemesterCourse(null);deps.setActiveSessionId(null);localStorage.setItem('redpen_active_workbook_id',saved.id);localStorage.removeItem('redpen_active_worksheet_id');deps.resetWorkspaceForImport();setShowOldSessionModal(false);if(deps.token)await deps.persistWorkbook(saved);setShowCourseSelector(true);}catch(error){console.error('Excel workbook import failed:',error);deps.setSessionSaveState('error');alert('We could not import this Excel workbook. Please make sure it is a valid RedPen workbook.');}finally{input.value='';}};input.click();};
 return {modalType,setModalType,pendingUpload,setPendingUpload,showOldSessionModal,setShowOldSessionModal,pendingGradeNavigation,setPendingGradeNavigation,showNewCourseModal,setShowNewCourseModal,showNewSessionModal,setShowNewSessionModal,showCourseSelector,setShowCourseSelector,openUploadModal,triggerPendingUpload,closeModal,handleSkipSemester,handleContinueSemester,handleStartNewFromContinue,handleCreateNewWorksheet,handleNewSemesterConfirm:handleCreateNewWorksheet,handleNewCourse,handleCreateNewWorkbook,loadOldSemester:selectWorksheet,handleViewChange,handleLoadFromFile,handleNewSession:handleCreateNewWorkbook};
}

export const useCourseSessionModals = useWorkbookModals;
