import { useState, useCallback, useEffect } from 'react';
import { StudentInfo } from '../types';
import type { RedPenWorkbook, RedPenWorksheet } from '../types/workbook';
import { worksheetIdentityKey, normalizeCourse } from '../lib/sessionStore';
import { createWorkbook, loadLocalWorkbook, writeLocalWorkbook, setActiveWorksheet, fetchCloudWorkbooks, saveCloudWorkbook, setWorkbookStorageScope } from '../lib/workbookStore';
import { fetchCloudHistory, writeLocalHistory } from '../lib/historyStore';
import { SemesterCourse } from '../components/CourseSessionModal';

export function useWorkbook(user: any, token: string | null, setStudentInfo: React.Dispatch<React.SetStateAction<StudentInfo>>, setHistory: (history: any[]) => void) {
    const [workbook, setWorkbook] = useState<RedPenWorkbook | null>(null);
    const [workbooks, setWorkbooks] = useState<RedPenWorkbook[]>([]);
    const [activeWorkbookId, setActiveWorkbookId] = useState<string | null>(null);
    const [worksheets, setWorksheets] = useState<SemesterCourse[]>([]);
    const [activeWorksheetId, setActiveWorksheetId] = useState<string | null>(null);
    const [activeCourse, setActiveCourse] = useState<SemesterCourse | null>(null);
    const [workbookSaveState, setWorkbookSaveState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle');
    const [showWorkbookStatus, setShowWorkbookStatus] = useState(false);
    const [searchTerm, setSearchTerm] = useState('');
    const ownerId = user?.id ? String(user.id) : null;
    const courses = workbook ? workbook.sheets.map(sheet => sheet.course).filter(course => course.courseCode?.trim()).map(course => ({ courseCode: course.courseCode.trim(), courseName: course.courseName || '' })) : [];
    const workbookCourses = workbook?.sheets || [];
    const filteredWorksheets = worksheets.filter(course => { const term = searchTerm.trim().toLowerCase(); if (!term) return true; return course.courseCode?.toLowerCase().includes(term) || course.courseName?.toLowerCase().includes(term) || course.customName?.toLowerCase().includes(term) || course.sessionLabel?.toLowerCase().includes(term); });
    const filteredCourses = workbookCourses.filter(sheet => searchTerm === '' || sheet.course.courseCode.toLowerCase().includes(searchTerm.toLowerCase()) || sheet.course.courseName?.toLowerCase().includes(searchTerm.toLowerCase()));
    const syncStudentInfoFromWorksheet = (worksheet: RedPenWorksheet | null) => { if (!worksheet) return; setStudentInfo(prev => ({ ...prev, courseCode: worksheet.course?.courseCode || '', year: worksheet.course?.year || '', semester: worksheet.course?.semester || '', academicYear: worksheet.course?.academicYear || '', program: worksheet.course?.program || prev.program })); };

    const persistWorksheet = useCallback(async (course: SemesterCourse): Promise<SemesterCourse | null> => {
        const normalized = normalizeCourse(course); const worksheetId = normalized.id || worksheetIdentityKey(normalized); const now = new Date().toISOString(); const currentWorkbook = workbook || createWorkbook('');
        const existingWorksheet = currentWorkbook.sheets.find(sheet => sheet.id === worksheetId || worksheetIdentityKey(sheet.course) === worksheetIdentityKey(normalized));
        const worksheet = existingWorksheet ? { ...existingWorksheet, id: existingWorksheet.id || worksheetId, name: normalized.courseCode || normalized.customName || existingWorksheet.name || 'Course', course: { ...existingWorksheet.course, ...normalized, id: existingWorksheet.id || worksheetId }, updatedAt: now } : { id: worksheetId, name: normalized.courseCode || normalized.customName || 'Course', course: { ...normalized, id: worksheetId }, rows: [], createdAt: normalized.createdAt || now, updatedAt: now };
        const nextWorkbook: RedPenWorkbook = { ...currentWorkbook, updatedAt: now, activeSheetId: worksheet.id, sheets: existingWorksheet ? currentWorkbook.sheets.map(sheet => sheet.id === existingWorksheet.id ? worksheet : sheet) : [...currentWorkbook.sheets, worksheet] };
        const savedLocalWorkbook = writeLocalWorkbook(nextWorkbook, ownerId); setWorkbook(savedLocalWorkbook); setWorkbooks(prev => [savedLocalWorkbook, ...prev.filter(item => item.id !== savedLocalWorkbook.id)]); setActiveWorkbookId(savedLocalWorkbook.id); setWorksheets(savedLocalWorkbook.sheets.map(sheet => normalizeCourse(sheet.course)));
        const activeWorksheet = savedLocalWorkbook.sheets.find(sheet => sheet.id === savedLocalWorkbook.activeSheetId); const selectedCourse = activeWorksheet ? normalizeCourse(activeWorksheet.course) : normalized;
        setActiveCourse(selectedCourse); setActiveWorksheetId(activeWorksheet?.id || worksheet.id); syncStudentInfoFromWorksheet(activeWorksheet || worksheet); localStorage.setItem('redpen_active_workbook_id', savedLocalWorkbook.id); localStorage.setItem('redpen_active_worksheet_id', activeWorksheet?.id || worksheet.id); setShowWorkbookStatus(true);
        if (!token) { setWorkbookSaveState('saved'); return selectedCourse; }
        setWorkbookSaveState('saving');
        try { const cloudResult = await saveCloudWorkbook(token, savedLocalWorkbook); const normalizedCloudWorkbook = writeLocalWorkbook(cloudResult.workbook, ownerId); setWorkbook(normalizedCloudWorkbook); setWorkbooks(cloudResult.workbooks?.map(write => writeLocalWorkbook(write, ownerId)) || [normalizedCloudWorkbook]); setActiveWorkbookId(normalizedCloudWorkbook.id); setWorksheets(normalizedCloudWorkbook.sheets.map(sheet => normalizeCourse(sheet.course))); const cloudActive = normalizedCloudWorkbook.sheets.find(sheet => sheet.id === normalizedCloudWorkbook.activeSheetId); if (cloudActive) { const cloudCourse = normalizeCourse(cloudActive.course); setActiveCourse(cloudCourse); setActiveWorksheetId(cloudActive.id); syncStudentInfoFromWorksheet(cloudActive); localStorage.setItem('redpen_active_worksheet_id', cloudActive.id); } localStorage.setItem('redpen_active_workbook_id', normalizedCloudWorkbook.id); setWorkbookSaveState('saved'); return cloudActive ? normalizeCourse(cloudActive.course) : selectedCourse; } catch (error) { console.error('Failed to save workbook to cloud:', error); setWorkbookSaveState('error'); return selectedCourse; }
    }, [workbook, token, ownerId]);

    const persistWorkbook = useCallback(async (nextWorkbook: RedPenWorkbook): Promise<RedPenWorkbook> => { const savedLocalWorkbook = writeLocalWorkbook(nextWorkbook, ownerId); setWorkbook(savedLocalWorkbook); setWorkbooks(prev => [savedLocalWorkbook, ...prev.filter(item => item.id !== savedLocalWorkbook.id)]); setActiveWorkbookId(savedLocalWorkbook.id); setWorksheets(savedLocalWorkbook.sheets.map(sheet => normalizeCourse(sheet.course))); setShowWorkbookStatus(true); localStorage.setItem('redpen_active_workbook_id', savedLocalWorkbook.id); if (!token) { setWorkbookSaveState('saved'); return savedLocalWorkbook; } setWorkbookSaveState('saving'); try { const cloudResult = await saveCloudWorkbook(token, savedLocalWorkbook); const savedCloudWorkbook = writeLocalWorkbook(cloudResult.workbook, ownerId); setWorkbook(savedCloudWorkbook); setWorkbooks(cloudResult.workbooks?.map(item => writeLocalWorkbook(item, ownerId)) || [savedCloudWorkbook]); setActiveWorkbookId(savedCloudWorkbook.id); setWorksheets(savedCloudWorkbook.sheets.map(sheet => normalizeCourse(sheet.course))); setWorkbookSaveState('saved'); return savedCloudWorkbook; } catch (error) { console.error('Failed to persist workbook:', error); setWorkbookSaveState('error'); return savedLocalWorkbook; } }, [token, ownerId]);

    const selectWorkbook = useCallback(async (workbookId: string): Promise<RedPenWorkbook | null> => {
        const selected = workbooks.find(item => item.id === workbookId);
        if (!selected) return null;
        const activeSheet = selected.activeSheetId ? selected.sheets.find(sheet => sheet.id === selected.activeSheetId) : selected.sheets[0] || null;
        const nextWorkbook = activeSheet && selected.activeSheetId !== activeSheet.id ? { ...selected, activeSheetId: activeSheet.id } : selected;
        const saved = writeLocalWorkbook(nextWorkbook, ownerId);
        setWorkbook(saved); setActiveWorkbookId(saved.id); setWorkbooks(prev => [saved, ...prev.filter(item => item.id !== saved.id)]); setWorksheets(saved.sheets.map(sheet => normalizeCourse(sheet.course))); setActiveWorksheetId(activeSheet?.id || null); setActiveCourse(activeSheet ? normalizeCourse(activeSheet.course) : null);
        localStorage.setItem('redpen_active_workbook_id', saved.id); if (activeSheet) { localStorage.setItem('redpen_active_worksheet_id', activeSheet.id); syncStudentInfoFromWorksheet(activeSheet); } else localStorage.removeItem('redpen_active_worksheet_id');
        setWorkbookSaveState('saved'); setShowWorkbookStatus(true); return saved;
    }, [workbooks, ownerId]);

    useEffect(() => { let cancelled = false; if (!user || !token || !ownerId) { setWorkbook(null); setWorkbooks([]); setActiveWorkbookId(null); setWorksheets([]); setActiveCourse(null); setActiveWorksheetId(null); setHistory([]); localStorage.removeItem('redpen_active_workbook_id'); localStorage.removeItem('redpen_active_worksheet_id'); setWorkbookSaveState('idle'); setShowWorkbookStatus(false); return () => { cancelled = true; }; } setWorkbookStorageScope(ownerId); const syncCloudData = async () => { try { const [cloudWorkbooks, cloudHistory] = await Promise.all([fetchCloudWorkbooks(token), fetchCloudHistory(token)]); if (cancelled) return; setHistory(cloudHistory); writeLocalHistory(cloudHistory); const localWorkbook = loadLocalWorkbook(ownerId); const storedActiveWorkbookId = localStorage.getItem('redpen_active_workbook_id'); let restoredWorkbook = storedActiveWorkbookId ? cloudWorkbooks.find(candidate => candidate.id === storedActiveWorkbookId) || (localWorkbook?.id === storedActiveWorkbookId ? localWorkbook : null) : null; if (!restoredWorkbook) { const matchingCloud = localWorkbook ? cloudWorkbooks.find(candidate => candidate.id === localWorkbook.id) : null; if (matchingCloud && localWorkbook) { const localTime = new Date(localWorkbook.updatedAt || 0).getTime(); const cloudTime = new Date(matchingCloud.updatedAt || 0).getTime(); if (localTime > cloudTime) { try { restoredWorkbook = (await saveCloudWorkbook(token, localWorkbook)).workbook; } catch { restoredWorkbook = localWorkbook; } } else restoredWorkbook = matchingCloud; } else if (localWorkbook) { restoredWorkbook = localWorkbook; try { restoredWorkbook = (await saveCloudWorkbook(token, localWorkbook)).workbook; } catch (error) { console.error('Failed to upload local workbook:', error); } } else restoredWorkbook = cloudWorkbooks[0] || null; }
            if (cancelled) return; setWorkbooks(cloudWorkbooks.length ? [restoredWorkbook!, ...cloudWorkbooks.filter(item => item.id !== restoredWorkbook?.id)] : restoredWorkbook ? [restoredWorkbook] : []); if (!restoredWorkbook) { setWorkbook(null); setActiveWorkbookId(null); setWorksheets([]); setActiveCourse(null); setActiveWorksheetId(null); localStorage.removeItem('redpen_active_workbook_id'); localStorage.removeItem('redpen_active_worksheet_id'); setWorkbookSaveState('saved'); return; } const activeWorksheet = restoredWorkbook.activeSheetId ? restoredWorkbook.sheets.find(sheet => sheet.id === restoredWorkbook.activeSheetId) : restoredWorkbook.sheets[0] || null; const normalizedWorkbook = { ...restoredWorkbook, activeSheetId: activeWorksheet?.id || null }; const savedWorkbook = writeLocalWorkbook(normalizedWorkbook, ownerId); setWorkbook(savedWorkbook); setActiveWorkbookId(savedWorkbook.id); setWorksheets(savedWorkbook.sheets.map(sheet => normalizeCourse(sheet.course))); if (activeWorksheet) { const normalized = normalizeCourse(activeWorksheet.course); setActiveCourse(normalized); setActiveWorksheetId(activeWorksheet.id); localStorage.setItem('redpen_active_worksheet_id', activeWorksheet.id); syncStudentInfoFromWorksheet(activeWorksheet); } else { setActiveCourse(null); setActiveWorksheetId(null); localStorage.removeItem('redpen_active_worksheet_id'); } localStorage.setItem('redpen_active_workbook_id', savedWorkbook.id); setWorkbookSaveState('saved'); } catch (error) { if (cancelled) return; console.error('Failed to restore workbook data:', error); const localWorkbook = loadLocalWorkbook(ownerId); if (localWorkbook) { setWorkbook(localWorkbook); setWorkbooks([localWorkbook]); setActiveWorkbookId(localWorkbook.id); setWorksheets(localWorkbook.sheets.map(sheet => normalizeCourse(sheet.course))); const activeWorksheet = localWorkbook.activeSheetId ? localWorkbook.sheets.find(sheet => sheet.id === localWorkbook.activeSheetId) : localWorkbook.sheets[0] || null; if (activeWorksheet) { const normalized = normalizeCourse(activeWorksheet.course); setActiveCourse(normalized); setActiveWorksheetId(activeWorksheet.id); syncStudentInfoFromWorksheet(activeWorksheet); } } else { setWorkbook(null); setWorkbooks([]); setActiveWorkbookId(null); setWorksheets([]); setActiveCourse(null); setActiveWorksheetId(null); } setWorkbookSaveState('error'); setShowWorkbookStatus(true); } }; syncCloudData(); return () => { cancelled = true; }; }, [user, token, ownerId]);

    useEffect(() => { if (!activeWorksheetId) { localStorage.removeItem('redpen_active_worksheet_id'); return; } localStorage.setItem('redpen_active_worksheet_id', activeWorksheetId); if (workbook && workbook.activeSheetId !== activeWorksheetId && workbook.sheets.some(sheet => sheet.id === activeWorksheetId)) setWorkbook(setActiveWorksheet(workbook, activeWorksheetId)); }, [activeWorksheetId, workbook]);
    const clearWorkbookState = () => { setActiveWorkbookId(null); setActiveWorksheetId(null); setActiveCourse(null); setWorkbook(null); };

    return { workbook, setWorkbook, workbooks, setWorkbooks, activeWorkbookId, setActiveWorkbookId, activeWorkbook: workbook, selectWorkbook, worksheets, setWorksheets, activeWorksheetId, setActiveWorksheetId, activeCourse, setActiveCourse, workbookSaveState, setWorkbookSaveState, showWorkbookStatus, setShowWorkbookStatus, searchTerm, setSearchTerm, courses, filteredWorksheets, workbookCourses, filteredCourses, syncStudentInfoFromWorksheet, persistWorksheet, persistWorkbook, clearWorkbookState,
        sessions: worksheets, setSessions: setWorksheets, activeSessionId: activeWorksheetId, setActiveSessionId: setActiveWorksheetId, semesterCourse: activeCourse, setSemesterCourse: setActiveCourse, sessionSaveState: workbookSaveState, setSessionSaveState: setWorkbookSaveState, showSessionStatus: showWorkbookStatus, setShowSessionStatus: setShowWorkbookStatus, filteredSessions: filteredWorksheets, persistSession: persistWorksheet };
}
