import React from 'react';
import { BookOpen, ChevronDown, Check, Plus } from 'lucide-react';
import { SemesterCourse } from './CourseSessionModal';
import { worksheetIdentityKey } from '../lib/sessionStore'; 

interface Props { sessions: SemesterCourse[]; activeSession: SemesterCourse | null; onSelect: (session: SemesterCourse) => void; onNewSession: () => void; disabled?: boolean; }
const courseTitle=(c:SemesterCourse)=>c.courseCode||c.customName||'Unnamed course';
const courseMeta=(c:SemesterCourse)=>[c.year,c.semester,c.academicYear].filter(Boolean).join(' · ');
export const ActiveSessionSelector=({sessions,activeSession,onSelect,onNewSession,disabled=false}:Props)=>{const [open,setOpen]=React.useState(false);const ref=React.useRef<HTMLDivElement>(null);React.useEffect(()=>{if(!open)return;const h=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',h);return()=>document.removeEventListener('mousedown',h)},[open]);const activeKey=activeSession?worksheetIdentityKey(activeSession):'';return <div ref={ref} className="relative min-w-[220px] max-w-[320px]"><button type="button" disabled={disabled} onClick={()=>setOpen(v=>!v)} className="w-full flex items-center gap-2 px-3 py-2 rounded-xl bg-gray-950/80 border border-gray-800 hover:border-accent-blue/40 disabled:opacity-50 transition-colors"><BookOpen size={14} className="text-accent-blue shrink-0"/><div className="min-w-0 flex-1 text-left"><div className="text-[9px] uppercase tracking-widest font-black text-gray-600">Active Workbook</div><div className="text-[11px] font-bold text-white truncate">{activeSession?courseTitle(activeSession):'No workbook selected'}</div>{activeSession&&courseMeta(activeSession)&&<div className="text-[9px] text-gray-600 truncate">{courseMeta(activeSession)}</div>}</div><ChevronDown size={14} className={`text-gray-600 ${open?'rotate-180':''}`}/></button>{open&&<div className="absolute left-0 right-0 top-full mt-2 z-[10000] bg-gray-950 border border-gray-800 rounded-xl shadow-2xl overflow-hidden"><div className="px-3 py-2 border-b border-gray-800"><p className="text-[9px] uppercase tracking-widest font-black text-gray-600">Workbooks</p></div><div className="max-h-[280px] overflow-y-auto p-1">{sessions.length===0?<div className="px-3 py-4 text-center text-[10px] text-gray-600">No workbooks yet.</div>:sessions.map(s=>{const key=worksheetIdentityKey(s),selected=key===activeKey;return <button key={s.id||key} type="button" onClick={()=>{setOpen(false);onSelect(s)}} className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-left ${selected?'bg-accent-blue/10':'hover:bg-white/5'}`}><div className="min-w-0 flex-1"><div className={`text-[11px] font-bold truncate ${selected?'text-accent-blue':'text-gray-300'}`}>{courseTitle(s)}</div>{courseMeta(s)&&<div className="text-[9px] text-gray-600 truncate">{courseMeta(s)}</div>}</div>{selected&&<Check size={13} className="text-accent-blue"/>}</button>})}</div><div className="border-t border-gray-800 p-1"><button type="button" onClick={()=>{setOpen(false);onNewSession()}} className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-[10px] font-bold text-gray-400 hover:text-white hover:bg-white/5"><Plus size={13}/>New Workbook</button></div></div>}</div>};
