import logo from '../assets/logo.png';
import React, { useState, useEffect, useRef } from 'react';
import { Search, SlidersHorizontal, RotateCw, Bot, Layers, FolderOpen, LogIn, LogOut, LayoutGrid, Zap, PenLine, History as HistoryIcon, User, Save, Printer, Plus, BookOpen, Check, HelpCircle } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { StudentInfo, HistoryRecord, SemesterCourse } from '../types';
import type { RedPenWorkbook } from '../types/workbook';

interface TopBarProps { workbooks: RedPenWorkbook[]; activeWorkbook: RedPenWorkbook | null; onSelectWorkbook: (workbook: RedPenWorkbook) => void; sessions: SemesterCourse[]; activeSession: SemesterCourse | null; onSelectSession: (session: SemesterCourse) => void; onLoadSessionFromFile: () => void; onNew: () => void; onNewCourse: () => void; onNewSession: () => void; onNewPaper: () => void; onSave: () => void; onPrint: () => void; onClearResult: () => void; onRefresh: () => void; onSettings: () => void; onBatch: () => void; hasResult: boolean; studentInfo: StudentInfo; onStudentInfoUpdate: (updates: Partial<StudentInfo>) => void; history: HistoryRecord[]; onShowOldSessions: () => void; onSearchTermChange: (term: string) => void; isLoggedIn: boolean; onLogin: () => void; onLogout: () => void; onToggleYaza: () => void; isYazaOpen: boolean; onViewChange: (view: 'dashboard' | 'grade' | 'history' | 'remark') => void; onProfile: () => void; onLoadRecord: (record: HistoryRecord) => void; }
interface DropdownItem { label?: string; action?: () => void; disabled?: boolean; divider?: boolean; active?: boolean; }
const workbookTitle = (w: RedPenWorkbook) => w.name?.trim() || 'Untitled Workbook';
const courseTitle = (c: SemesterCourse) => c.courseCode || c.customName || 'Unnamed course';
const courseMeta = (c: SemesterCourse) => [c.courseName, c.year, c.semester, c.academicYear].filter(Boolean).join(' · ');

const Dropdown = ({ x, items, onClose }: { x: number; items: DropdownItem[]; onClose: () => void }) => { const ref = useRef<HTMLDivElement>(null); useEffect(() => { const h = (e: MouseEvent) => { if (ref.current && !ref.current.contains(e.target as Node)) onClose(); }; document.addEventListener('mousedown', h); return () => document.removeEventListener('mousedown', h); }, [onClose]); return <motion.div ref={ref} initial={{ opacity: 0, y: -6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }} style={{ position: 'fixed', top: 40, left: x, zIndex: 9999, minWidth: 260 }} className="bg-gray-950 border border-gray-800 rounded-xl shadow-2xl py-1 overflow-hidden">{items.map((item, i) => item.divider ? <div key={i} className="my-1 border-t border-gray-800/70" /> : <button key={i} disabled={item.disabled} onClick={() => { if (!item.disabled && item.action) { item.action(); onClose(); } }} className={`w-full text-left px-4 py-1.5 text-[11px] font-medium flex items-center justify-between ${item.disabled ? 'text-gray-700 cursor-not-allowed' : item.active ? 'text-accent-blue bg-accent-blue/10' : 'text-gray-300 hover:bg-white/5 hover:text-white'}`}><span className="truncate">{item.label}</span>{item.active && <Check size={13} />}</button>)}</motion.div>; };

export const TopBar = (props: TopBarProps) => {
  const { workbooks, activeWorkbook, onSelectWorkbook, sessions, activeSession, onSelectSession, onLoadSessionFromFile, onNew, onNewCourse, onNewSession, onNewPaper, onSave, onPrint, onClearResult, onRefresh, onSettings, onBatch, hasResult, studentInfo, onStudentInfoUpdate, history, onShowOldSessions, onSearchTermChange, isLoggedIn, onLogin, onLogout, onToggleYaza, isYazaOpen, onViewChange, onProfile, onLoadRecord } = props;
  const [menu, setMenu] = useState<{ name: string; x: number } | null>(null); const [query, setQuery] = useState('');
  const openMenu = (name: string, e: React.MouseEvent<HTMLButtonElement>) => { const r = e.currentTarget.getBoundingClientRect(); setMenu(menu?.name === name ? null : { name, x: r.left }); };
  useEffect(() => { document.documentElement.dataset.redpenWorkbookActive = activeWorkbook ? 'true' : 'false'; return () => { delete document.documentElement.dataset.redpenWorkbookActive; }; }, [activeWorkbook]);
  useEffect(() => { const h = () => onShowOldSessions(); window.addEventListener('redpen:open-load-workbook', h); return () => window.removeEventListener('redpen:open-load-workbook', h); }, [onShowOldSessions]);

  const workbookItems: DropdownItem[] = workbooks.map(w => ({ label: `${workbookTitle(w)} · ${w.sheets?.length || 0} ${(w.sheets?.length || 0) === 1 ? 'course' : 'courses'}`, action: () => onSelectWorkbook(w), active: activeWorkbook?.id === w.id }));
  const workbookMenu: DropdownItem[] = [{ label: 'Current Workbook', disabled: true }, ...(activeWorkbook ? [{ label: workbookTitle(activeWorkbook), disabled: true, active: true }] : [{ label: 'No workbook selected', disabled: true }]), { divider: true }, { label: 'Switch Workbook', disabled: true }, ...(workbookItems.length ? workbookItems : [{ label: 'No workbooks yet', disabled: true }]), { divider: true }, { label: 'New Workbook', action: onNewSession }, { label: 'Load Workbook from File', action: onLoadSessionFromFile }];
  const courseSheets = activeWorkbook?.sheets || [];
  const courseItems: DropdownItem[] = courseSheets.map(sheet => ({ label: `${courseTitle(sheet.course)}${courseMeta(sheet.course) ? ` · ${courseMeta(sheet.course)}` : ''}`, action: () => onSelectSession(sheet.course), active: !!activeSession && sheet.id === activeWorkbook?.activeSheetId }));
  const courseMenu: DropdownItem[] = [{ label: 'Current Course', disabled: true }, ...(activeSession ? [{ label: courseTitle(activeSession), disabled: true, active: true }] : [{ label: 'No course selected', disabled: true }]), { divider: true }, ...(courseItems.length ? courseItems : [{ label: 'No courses available in this workbook', disabled: true }]), { divider: true }, { label: 'New Course', action: onNewCourse }];
  const studentMenu: DropdownItem[] = [{ label: 'Current Student', disabled: true }, { label: studentInfo.name || 'No student entered', disabled: true }, ...(studentInfo.regNo ? [{ label: `Reg: ${studentInfo.regNo}`, disabled: true }] : []), { divider: true }, { label: 'Switch Student', action: () => onViewChange('history') }, { label: 'New Student', action: () => { if (!activeWorkbook) { onShowOldSessions(); return; } onNewPaper(); onStudentInfoUpdate({ examDate: '' }); } }];
  const menus: Record<string, DropdownItem[]> = { File: [{ label: 'Save Results', action: onSave, disabled: !hasResult }, { label: 'Print Report', action: onPrint, disabled: !hasResult }], Edit: [{ label: 'Clear Results', action: onClearResult, disabled: !hasResult }, { divider: true }, { label: 'Reset All', action: onNew }], Workbook: workbookMenu, Course: courseMenu, Placeholder: [{ label: 'Placeholder', disabled: true }], Student: studentMenu };
  const actions = [{ label: 'Dashboard', icon: LayoutGrid, action: () => onViewChange('dashboard') }, { label: 'Grade', icon: Zap, action: () => activeSession ? onViewChange('grade') : onShowOldSessions() }, { label: 'Remark', icon: PenLine, action: () => onViewChange('remark') }, { label: 'History', icon: HistoryIcon, action: () => onViewChange('history') }, { label: 'Profile', icon: User, action: onProfile }, { label: 'New Workbook', icon: BookOpen, action: onNewSession }, { label: 'New Course', icon: Plus, action: onNewCourse }, { label: 'New Paper', icon: FolderOpen, action: onNewPaper }, { label: 'Save Results', icon: Save, action: onSave }, { label: 'Print Report', icon: Printer, action: onPrint }, { label: 'Batch Grading', icon: Layers, action: onBatch }, { label: 'Settings', icon: SlidersHorizontal, action: onSettings }, { label: 'Help', icon: HelpCircle, action: () => window.dispatchEvent(new Event('redpen:open-help')) }];
  const matches = query ? actions.filter(a => a.label.toLowerCase().includes(query.toLowerCase())).slice(0, 6) : [];
  return <div className="h-10 bg-sidebar border-b border-gray-800 flex items-center px-4 gap-4 select-none"><div className="flex items-center gap-1.5 shrink-0"><img src={logo} alt="Logo" className="w-18 h-8 object-contain" /><div className="flex gap-0.5 text-[11px] font-medium text-gray-400 ml-2">{['File','Edit','Workbook','Course','Placeholder','Student'].map(name => <button key={name} onClick={e => openMenu(name, e)} className={`px-2 py-1 rounded ${menu?.name === name ? 'text-white bg-white/10' : 'hover:text-white hover:bg-white/5'}`}>{name}</button>)}</div></div><div className="flex-1 flex justify-center"><div className="relative w-full max-w-lg"><Search className="absolute left-3 top-1.5 text-gray-500" size={12}/><input value={query} onChange={e => { setQuery(e.target.value); onSearchTermChange(e.target.value); }} placeholder="Search actions, students, or courses" className="w-full bg-[#252526] border border-[#3e3e42] rounded-md py-1 pl-9 pr-3 text-[11px] text-ink focus:border-accent-blue focus:outline-none"/>{query && matches.length > 0 && <div className="absolute top-full left-0 right-0 mt-1 z-[9999] bg-gray-950 border border-gray-800 rounded-xl overflow-hidden">{matches.map((a, i) => <button key={i} onClick={() => { a.action(); setQuery(''); }} className="w-full text-left px-4 py-2 text-[11px] text-gray-300 hover:bg-white/5 flex gap-2"><a.icon size={13}/>{a.label}</button>)}</div>}</div></div><div className="flex items-center gap-2 shrink-0"><button onClick={isLoggedIn ? onLogout : onLogin} className="px-3 py-1 bg-gray-700 text-white text-[11px] font-bold rounded-md flex items-center gap-1.5">{isLoggedIn ? <LogOut size={12}/> : <LogIn size={12}/>} {isLoggedIn ? 'Logout' : 'Login'}</button><button onClick={onToggleYaza} className="px-3 py-1 bg-gray-700 text-white text-[11px] font-bold rounded-md flex items-center gap-1.5"><Bot size={12}/> Yaza AI</button><button onClick={() => window.dispatchEvent(new Event('redpen:open-help'))} className="px-3 py-1 bg-accent-blue text-white text-[11px] font-bold rounded-md flex items-center gap-1.5"><HelpCircle size={12}/> Help</button><button onClick={onRefresh} className="px-3 py-1 bg-yellow-600 text-white text-[11px] font-bold rounded-md flex items-center gap-1.5"><RotateCw size={10}/> Refresh</button><button onClick={onSettings} className="px-3 py-1 bg-accent-blue text-white text-[11px] font-bold rounded-md flex items-center gap-1"><SlidersHorizontal size={10}/> Settings</button></div><AnimatePresence>{menu && <Dropdown x={menu.x} items={menus[menu.name]} onClose={() => setMenu(null)}/>}</AnimatePresence></div>;
};
